"""External service clients."""

from src.services.health import HealthService, health_service
from src.services.service_manager import (
    get_agent_service,
    get_emotion_motion_mapper,
    get_ltm_service,
    get_mongo_client,
    get_mongo_db,
    get_pending_task_repo,
    get_session_registry,
    get_summary_service,
    get_tts_service,
    get_user_profile_service,
    initialize_agent_service,
    initialize_channel_service,
    initialize_emotion_motion_mapper,
    initialize_ltm_service,
    initialize_mongodb_client,
    initialize_services,
    initialize_summary_service,
    initialize_sweep_service,
    initialize_tts_service,
    initialize_user_profile_service,
)

__all__ = [
    "HealthService",
    "get_agent_service",
    "get_emotion_motion_mapper",
    "get_ltm_service",
    "get_mongo_client",
    "get_mongo_db",
    "get_pending_task_repo",
    "get_session_registry",
    "get_summary_service",
    "get_tts_service",
    "get_user_profile_service",
    "health_service",
    "initialize_agent_service",
    "initialize_channel_service",
    "initialize_emotion_motion_mapper",
    "initialize_ltm_service",
    "initialize_mongodb_client",
    "initialize_services",
    "initialize_summary_service",
    "initialize_sweep_service",
    "initialize_tts_service",
    "initialize_user_profile_service",
]
